#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    arr = []
    for i in range(0,len(bill)):
        for j in range(0,k):
           arr.append(bill[j])
        for d in range(k+1,len(bill)):
            arr.append(bill[d])
        break
    print(arr)
   
    x = sum(arr)
    print(x)
    
    y = x/2
    print(y)
    
    if y != b:
        print(abs(y-b))
    elif y == b:
        print("Bon Appetit")

if __name__ == '__main__':
    nk = input().rstrip().split()

    n = int(nk[0])

    k = int(nk[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
