#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    max = scores[0]
    maxarr = []
    min = scores[0]
    minarr = []
    for i in range(1,len(scores)):
        if scores[i]>max:
            max = scores[i]
            maxarr.append(max)
    for i in range(1,len(scores)):
        if scores[i]<min:
           min = scores[i]
           minarr.append(min)
    print(len(maxarr),len(minarr))
        


if __name__ == '__main__':

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    
