#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    count = 0
    count1 = 0
    for i in range(0,len(a) and len(b)):
        if a[i]>b[i]:
            count = count+1
        elif a[i]<b[i]:
            count1 = count1+1
        else:
            pass
    print(count , count1)

if __name__ == '__main__':

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

   
