#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    count = 0
    valley = 0
    for i in range(0,len(s)):
        if s[i]=='U':
            count=count+1
            if count ==0:
                valley = valley+1
                
        elif s[i]=='D':
            count = count-1
    print(valley)
        

        
if __name__ == '__main__':
    
    n = int(input())

    s = input()

    result = countingValleys(n, s)

   
