#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr):
    temp = []
    while(len(arr)>0):
        arr.sort()
        x = arr[0]
        print(len(arr))
        
        temp = arr
        arr= [] 
        for i in range(0,len(temp)):
            if temp[i]-x !=0:
                arr.append(temp[i]-x)    
   
        

if __name__ == '__main__':
   

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

   
