#!/bin/python3

import os
import sys


def pageCount(n, p):
   
    x = n//2
    
    y = p//2
   
    print(min(y,x-y))

if __name__ == '__main__':
   

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    
