#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the squares function below.
def squares(a, b):
    a = math.ceil(math.sqrt(a))
    b = math.floor(math.sqrt(b))
    print(b-a+1)
    
                
            
if __name__ == '__main__':
    

    q = int(input())

    for q_itr in range(q):
        ab = input().split()

        a = int(ab[0])

        b = int(ab[1])

        result = squares(a, b)
