#!/bin/python3

import math
import os
import random
import re
import sys

def viralAdvertising(n):
    cumulative = 0
    x = 5
    arr = []
    for i in range(0,n):
            shared = x//2
            liked = shared
            cumulative  = cumulative +liked
            
            x = (x//2) * 3
            arr.append(cumulative)
            
        
    print(max(arr))

if __name__ == '__main__':
    

    n = int(input())

    result = viralAdvertising(n)

   
